name: walrus
version: "0.9991"
license: "BSD-3-Clause"
date: 2022-02-21
description: |
    A new approach to proving hyperbolicity

authors:
    - name: Markus Pfeiffer
      url: http://www.morphism.de/~markusp/

maintainers:
    - name: Markus Pfeiffer
      url: http://www.morphism.de/~markusp/

GAP: ">= 4.10"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "datastructures"
      version: "0.2.2"
      url: "https://gap-packages.github.io/datastructures"
    - name: "digraphs"
      version: ">= 0.10"
      url: "https://digraphs.github.io/Digraphs"

suggested-pkgs:
    - name: "profiling"
      version: " >= 1.3.0"
      url: "https://gap-packages.github.io/profiling/"
    - name: "kbmag"
      version: ">= 1.5.4"
      url: "https://gap-packages.github.io/kbmag"

www: https://gap-packages.github.io/walrus
readme: README.md
packageinfo: https://gap-packages.github.io/walrus/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/walrus/releases/download/v0.9991/walrus-0.9991.tar.gz

abstract: |
    An implementation of hyperbolicity testing using an ideas
    by Derek Holt, Max Neunhöffer, Richard Parker, and Colva Roney-Dougal,
    and probably quite a few more

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Finitely Generated, group, monoid, hyperbolic.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Pfe22</span>]   <b class='BibAuthor'>Pfeiffer, M.</b>,
     <i class='BibTitle'>walrus, A new approach to proving hyperbolicity,
             Version 0.9991</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/walrus">https://gap-packages.github.io/walrus</a></span>.
    </p>
    

bibtex: |
    @misc{ walrus0.9991,
      author =           {Pfeiffer, M.},
      title =            {{walrus},  A  new  approach  to proving hyperbolicity,
                          {V}ersion 0.9991},
      month =            {Feb},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href          {https://gap-packages.github.io/walrus}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{walrus}}},
      keywords =         {Finitely Generated; group; monoid; hyperbolic},
      printedkey =       {Pfe22}
    }

